const doc = {
  info: {
    title: 'API Documentation',
    description: 'Automatically generated by Swagger Autogen'
  },
  host: 'localhost:4004',
  schemes: ['http']
}

const outputFile = './swagger_output.json'
const endpointsFiles = [
  "./src/index.ts"
]

const runSwagger = async () => {
  try {
    const swaggerAutogen = await (await import('swagger-autogen')).default
    swaggerAutogen(outputFile, endpointsFiles, doc)
  } catch (error) {}
}

runSwagger()