name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Packages Installation
        run: npm install # or any other build command

      - name: Run Build Checks
        run: npm run build # or any other build command

      - name: SSH into GC VM and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GC_VM_HOST }}
          username: ${{ secrets.GC_VM_USER }}
          key: ${{ secrets.GC_VM_PRIVATE_KEY }}
          port: 22
          script: |
            cd Nodejs
            git pull origin main
            cp ../.env .  # Copy .env from the parent directory to the Nodejs folder
            docker compose down
            docker compose build
            docker compose up -d
